version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/tools"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/git-chglog/git-chglog
    versions:
    - 0.14.2
  - dependency-name: github.com/sanemat/go-xgoinstall
    versions:
    - 0.2.0
  - dependency-name: github.com/sanemat/go-importlist
    versions:
    - 0.2.0
