name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: setup env unix
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
      - name: checkout
        uses: actions/checkout@v4
      - name: deps
        run: make install-tools
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: make crossbuild upload
