name: release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: setup env unix
        run: |
          echo "GOPATH=${{ runner.workspace }}/go" >> $GITHUB_ENV
          echo "${{ runner.workspace }}/go/bin" >> $GITHUB_PATH
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          path: go/src/github.com/${{ github.repository }}
      - name: deps
        run: make install-tools
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: make crossbuild upload
